[package]
name = "builder"
version = "0.1.0"
edition = "2021"

[dependencies]
pulldown-cmark = "0.13.0"
tera = "1.17.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.5.4", features = ["derive"] }
walkdir = "2.3.2"