name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install rust
        uses: dtolnay/rust-toolchain@stable

      - name: Temporarily remove dist from .gitignore
        run: sed -i '/dist/d' .gitignore

      - name: Build
        run: cargo run --manifest-path ./builder/Cargo.toml -- -u circuitgame_tutorial

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true